kitchen_core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .models import DishType, Cook
from .views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishTypeDetailView,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishDetailView,
    CookListView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    CookDetailView,
    ToggleAssignToDishView,
)

app_name = "kitchen_core"


urlpatterns = [
    path("", index, name="index"),
    path("dish_type/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_type/create", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_type/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish_type/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dish_type/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),

    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/<int:pk>/toggle-assign/", ToggleAssignToDishView.as_view(), name="toggle-assign-dish"),

    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
]

kitchen_core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.conf import settings


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )

class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ('years_of_experience', )

    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name}"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=7)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes",
    )
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )


    def get_absolute_url(self):
        return reverse("kitchen_core:dish-detail", args=[str(self.id)])






kitchen_core/forms.py
from django.contrib.auth.forms import UserCreationForm

from kitchen_core.models import Cook, DishType
from django import forms


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "username",
            "first_name",
            "last_name",
            "years_of_experience"
        )



class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by Name"}),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by Name"
            }
        )
    )

class CookSearchForm(forms.Form):
    cook = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "First Name or Last Name"
            }
        )
    )

class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["username", "first_name", "last_name", "years_of_experience", "email"]

kitchen_core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic, View
from .forms import CookCreationForm, DishSearchForm, DishTypeSearchForm, CookSearchForm, CookUpdateForm

from .models import Dish, DishType, Cook

@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_cooks": num_cooks,
        "num_visits": num_visits,
    }
    return render(request, "kitchen_core/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    paginate_by = 5
    template_name = "kitchen_core/dish_type_list.html"

    def get_context_data(self, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data['name'])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen_core:dish-type-list")
    template_name = "kitchen_core/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
     model = DishType
     fields = "__all__"
     template_name = "kitchen_core/dish_type_form.html"
     success_url = reverse_lazy("kitchen_core:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen_core/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen_core:dish-type-list")


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "kitchen_core/dish_type_detail.html"
    context_object_name = "dish_type"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dishes"] = self.object.dishes.all()

        return context


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    context_object_name = "dish_list"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name},
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type").prefetch_related("cooks")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("kitchen_core:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    success_url = reverse_lazy("kitchen_core:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen_core:dish-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish

@method_decorator(login_required, name='dispatch')
class ToggleAssignToDishView(View):
    def post(self, request, pk):
        cook = get_object_or_404(Cook, id=request.user.id)
        dish = get_object_or_404(Dish, id=pk)

        if cook in dish.cooks.all():
            dish.cooks.remove(cook)
        else:
            dish.cooks.add(cook)

        return HttpResponseRedirect(reverse_lazy("kitchen_core:dish-list"))



class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    context_object_name = "cook_list"
    template_name = "kitchen_core/cook_list.html"
    paginate_by = 5


    def get_context_data(self, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        cook = self.request.GET.get("cook", "")
        context["search_form"] = CookSearchForm(
            initial={"cook": cook},
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            cook_query = form.cleaned_data.get("cook", "")
            queryset = queryset.filter(
                Q(first_name__icontains=cook_query) |
                Q(last_name__icontains=cook_query)
            )
        return queryset

class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen_core:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen_core:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen_core:cook-list")


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


templates/kitchen_core/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <p class="text-warning">
    ⚠️ Are you sure you want to permanently delete this chef and associated dishes?
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'kitchen_core:dish-type-list' %}" class="btn btn-secondary">No, go back</a>

  </form>
{% endblock %}

templates/kitchen_core/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ cook.username }}
      <a href="{% url 'kitchen_core:cook-update' pk=cook.id %}" class="btn btn-warning link-to-page">
        update
      </a>
      <a href="{% url 'kitchen_core:cook-delete' pk=cook.id %}" class="btn btn-outline-danger link-to-page">
        Delete
      </a>
  </h1>
  <h2>Cook: {{ cook.first_name }} {{ cook.last_name }} </h2>
  <p>Experience {{ cook.years_of_experience }} years</p>
  <div class="ml-3">
    <h4>Dish</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Name:</strong> {{ dish.name }}</p>
        <p><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>

    {% empty %}
      <p>No dish!</p>
    {% endfor %}
  </div>
{% endblock %}


templates/kitchen_core/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen_core/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Cook list
    <a class="btn btn-primary link-to-page" href="{% url 'kitchen_core:cook-create' %}">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
  {{ search_form|crispy }}
  <input class="btn btn-secondary" type="submit" value="🔎">
  </form>


  {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Full Name</th>
        <th>Experience</th>
        <th>Create</th>
        <th>Delete</th>
      </tr>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td>
            <a href="{% url 'kitchen_core:cook-detail' pk=cook.id %}">
              {{ cook.username }}
            </a>
          </td>
          <td>{{ cook.first_name }} {{ cook.last_name }}</td>
          <td>{{ cook.years_of_experience }}</td>
          <td>
            <a href="{% url 'kitchen_core:cook-update' pk=cook.id %}">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'kitchen_core:cook-delete' pk=cook.id %}">
              Delete
            </a>
          </td>
          <td><a href="{% url 'kitchen_core:cook-detail' pk=cook.id %}"></a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>According to your criteria, there is no cook.</p>
  {% endif %}
{% endblock %}

templates/kitchen_core/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <p class="text-warning">
    ⚠️ Are you sure you want to permanently delete this dish?
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'kitchen_core:dish-list' %}" class="btn btn-secondary">No, go back</a>

  </form>
{% endblock %}

templates/kitchen_core/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-4">
  <div class="row mb-3">
    <div class="col">
      <h1>{{ dish.name }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <h5 class="mb-3">Описание</h5>
      <p>{{ dish.description }}</p>

      <h5 class="mt-4">Тип блюда</h5>
      <p>{{ dish.dish_type.name }}</p>

      {% if user.is_authenticated %}
        <form method="post" action="{% url 'kitchen_core:toggle-assign-dish' dish.pk %}">
          {% csrf_token %}
          {% if dish in user.dishes.all %}
            <button type="submit" class="btn btn-danger">Удалить из моих блюд</button>
          {% else %}
            <button type="submit" class="btn btn-success">Добавить в мои блюда</button>
          {% endif %}
        </form>
      {% endif %}
    </div>

    <div class="col-md-4 text-center">
      {% if dish.image %}
        <img src="{{ dish.image.url }}" alt="{{ dish.name }}" class="img-fluid rounded shadow">
      {% else %}
        <img src="{% static 'images/images.jpg' %}" alt="Нет изображения" class="img-fluid rounded shadow">
      {% endif %}
    </div>
  </div>

  <!-- Нижняя часть: кнопки редактирования и удаления -->
  <div class="row mt-4">
    <div class="col">
      <a href="{% url 'kitchen_core:dish-update' pk=dish.pk %}" class="btn btn-warning">Редактировать</a>
      <a href="{% url 'kitchen_core:dish-delete' pk=dish.pk %}" class="btn btn-outline-danger">Удалить</a>
    </div>
  </div>
</div>
{% endblock %}

templates/kitchen_core/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen_core/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish List
    <a class="btn btn-primary link-to-page" href="{% url 'kitchen_core:dish-create' %}">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
 
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>DishType</th>
        <th>Cook</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for dish in dish_list %}
        <tr>
          <td>{{ dish.id }}</td>
          <td><a href="{% url 'kitchen_core:dish-detail' pk=dish.id %}">{{ dish.name }}</a></td>
          <td>{{ dish.dish_type.name }}</td>
          <td>
            {% for cook in dish.cooks.all %}
              {{ cook.first_name }} {{ cook.last_name }}{% if not forloop.last %}, {% endif %}
            {% empty %}
              <em>No cooks</em>
            {% endfor %}
          </td>

          <td>
            <a href="{% url 'kitchen_core:dish-update' pk=dish.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
              href="{% url 'kitchen_core:dish-delete' pk=dish.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no such dishes in the kitchen!</p>
  {% endif %}
{% endblock %}

templates/kitchen_core/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <p class="text-warning">
    ⚠️ Are you sure you want to permanently delete this dish type and its associated dishes?
  </p>
  <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'kitchen_core:dish-type-list' %}" class="btn btn-secondary">No, go back</a>

  </form>
{% endblock %}

templates/kitchen_core/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish_type.name }}
      <a href="{% url 'kitchen_core:dish-type-update' pk=dish_type.pk %}" class="btn btn-warning link-to-page">
        update
      </a>
      <a href="{% url 'kitchen_core:dish-type-delete' pk=dish_type.pk %}" class="btn btn-outline-danger link-to-page">
        Delete
      </a>
  </h1>
  {% if dishes %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {% for dish in dishes %}
          <tr>
            <td>{{ dish.name }}</td>
            <td>{{ dish.price }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No dishes available for this type.</p>
  {% endif %}
{% endblock %}

templates/kitchen_core/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}


templates/kitchen_core/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish Type List
    <a class="btn btn-primary" href="{% url 'kitchen_core:dish-type-create' %}">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>

  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for dish_type in dish_type_list %}
        <tr>
          <td>{{ dish_type.id }}</td>
          <td>
            <a href="{% url 'kitchen_core:dish-type-detail' pk=dish_type.id %}">
              {{ dish_type.name }}
            </a>
          </td>
          <td>
            <a href="{% url 'kitchen_core:dish-type-update' pk=dish_type.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
              href="{% url 'kitchen_core:dish-type-delete' pk=dish_type.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no such dishes in the kitchen!</p>
  {% endif %}
{% endblock %}